name: Generate Protos

on:
  push:
    branches: [ main ]
    paths:
      - "proto/**"
      - "buf.yaml"
      - "buf.gen.yaml"
      - "buf.lock"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Обязательно для пуша изменений

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Нужно для правильной работы git

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1

      - name: Generate Protobuf code
        run: buf generate proto  # Явно указываем input (proto директория)

      - name: Commit and push generated files if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(proto): regenerate code"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions@github.com
          commit_author: github-actions[bot] <github-actions@github.com>
          file_pattern: gen/go/**  # Коммитим только сгенерированные файлы